# Generated by Django 4.2 on 2026-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        # This migration is intentionally empty to avoid field type conflicts
        # BigAutoField fields in models.py are correct for Django 6.0
    ]
